### ISSUE TITLE
透明不规则方块

### ISSUE THREAD

**Issue by wzh656** [wzh656/MinecraftWeb#3]
透明方块（如：仙人掌）显示bug

**Comment by jason-bowen-zheng** [comment]
好像不止仙人掌. 为啥命令方块放置后再破坏碰撞检测会无视命令方块直接返回命令方块后的方块.

要解决仙人掌之类的 bug. 得运用 GLSL(OpenGL 着色器语言, 类似 C 语言)的`discard`语句.
> 当然不止`discard`要写(OpenGL, 我不太清楚WebGL是啥, 自己百度一下)
我 GLSL 已经写好了, 但是还没有找到方法运行

**Comment by jason-bowen-zheng** [comment]
在 pyglet 中, 透明的 .png 贴图的透明部分是被忽略的, OpenGL 本身就支持 .png 的贴图.
但是在WebGL中, 我反正没有用过, 所以我不清楚, 建议百度一下.
> 最后, 不要用Windows自带的画图打开有透明部分的 png 文件

**Comment by wzh656** [comment]
这不是指无法显示透明图片，而是因为仙人掌🌵不是普通立方体而是不规则的，像立方体一样显示会很怪异（你可以试试）

**Comment by jason-bowen-zheng** [comment]
啊, 我知道为什么, 请先凑合着看下面几行绘制方块的代码:
```python
x, y, z = position
vertex_data = cube_vertices(x, y, z, 0.5)
texture_data = list(texture)
self._shown[position] = self.batch3d.add(24, GL_QUADS, self.group,
('v3f/static', vertex_data),
('t2f/static', texture_data))
```
Minecraft 基岩版和 Java 版的绘制方块远比这个麻烦, 我们绘制方块的方法是这样的:
```
1/2. 获取贴图
2/1. 创建一个 1*1*1 的正方体
3. 在正方体表面绘制贴图
4. 显示
```
就是这么简单. 可是仙人掌并不是一个标准 1\*1\*1 的正方体, 它的碰撞箱比 1\*1\*1 的略微小一点(你的贴图应该是仙人掌周围是透明色). 这就导致上面这几行绘制出来的方块周围会有间隙(一定是这个原因, 即使我没有试过).
这个返回顶点的`cube_vertices()`函数只支持标准的 1\*1\*1 正方体, 太复杂了, 这是这个项目中几个我看不懂的地方之一:
```python
def cube_vertices(x, y, z, n):
    # 返回在 x, y, z 坐标的方形顶点
    return [
        x-n,y+n,z-n, x-n,y+n,z+n, x+n,y+n,z+n, x+n,y+n,z-n,  # 顶部
        x-n,y-n,z-n, x+n,y-n,z-n, x+n,y-n,z+n, x-n,y-n,z+n,  # 底部
        x-n,y-n,z-n, x-n,y-n,z+n, x-n,y+n,z+n, x-n,y+n,z-n,  # 左边
        x+n,y-n,z+n, x+n,y-n,z-n, x+n,y+n,z-n, x+n,y+n,z+n,  # 右边
        x-n,y-n,z+n, x+n,y-n,z+n, x+n,y+n,z+n, x-n,y+n,z+n,  # 前面
        x+n,y-n,z-n, x-n,y-n,z-n, x-n,y+n,z-n, x+n,y+n,z-n,  # 后面
    ]
```
我想你用 THREE.js 创建的方体也都是同样大小的吧, 虽然你的每个方块都可以看成是一个个对象(我的方块只是一张张小贴图), 但是并没有定义它有多长, 多宽, 多高(原版的附魔台就是另一个例子, 它的高比一般的方块都要矮一点, 半砖和台阶也一样, 我不希望创建一个`stair_vertices()`的函数).

**Comment by wzh656** [comment]
这不仅仅是大小问题（大小问题已被解决，for example 我的橡木不到1m，because 现实的树干没有这么大），而是一个极其不规则的，表面凹凸不平的，必须将方块和贴图分成多个面或多个立方体组合起来的方块（但我懒得去试，大不了先不要这个方块了）

**Comment by jason-bowen-zheng** [comment]
谁跟你说仙人掌表明凹凸不平的? 我特地打开基岩版看了一下, 只是四角的贴图造成了这种效果, 可能 THREE 不能做成这样:
![screenshot_1599384288](https://user-images.githubusercontent.com/58848782/92322784-edc9a600-f065-11ea-97d6-f42f48fd9f14.jpg)
只是网易中国版, 国际版1.15. 不知道1.16. 我从1.16基岩版资源文件夹翻了半天也没有找到仙人掌的贴图.
> 您的资源文件非常不全, 还缺少行为文件
你应该不知道, 人物的 3D 效果使用的是两层贴图. 方块也是可以参考一下的.
为了不再继续暴露个人隐私, 我把计分版关了

**Comment by wzh656** [comment]
好吧，太久没玩过了（两三年了），话说你有电脑版的Minecraft（不是网易）吗？
应该可以双层贴图（或者说在方块外在弄点刺方块？）
And what's 行为文件？

**Comment by jason-bowen-zheng** [comment]
电脑版, 因为 Linux 的 Java 安装更方便, 所以安装在 Arch Linux 上了, 然后安装了 HMCL 启动器, 就是上次系统全面更新(`sudo pacman -Syu`)的时候更到一半关机了, 导致内核下载了但没有更新, 所以连命令行都进不去, 别提玩图形界面的游戏了, 但是紧急修复盘又坏了, 刻了一个最新的, 发现连不上网.
> 手机上有个 McinaBox 可以运行 Java 版, 就是我每次启动游戏都闪退

行为文件, 我为了研究基岩版的工作原理, 分别下载了原版基岩版的行为文件和资源文件, 行为文件就是控制实体(比如说生物)的json文件.
> 您的资源文件也是非常不齐全, 有些贴图根本没有找到, 导致得重新到 wiki 上搜刮.

**Comment by wzh656** [comment]
json怎么控制实体？保存什么信息吗？And我只用了`deskgood`控制玩家。
资源文件不全那也没办法，毕竟那些贴图都是我从百度上找的，有些贴图（比如基岩）我自己也找不到啊（wiki上有贴图？）

**Comment by jason-bowen-zheng** [comment]
wiki 上有一个`blockcss.png`的文件, 有所有方块的贴图, 手机上有个很老的`terrain.png`:
![terrain](https://user-images.githubusercontent.com/58848782/93664599-d0073280-faa2-11ea-94b6-369bfef28018.png)

在<https://github.com/Mouse0w0/MinecraftDeveloperGuide>有行为包和材质包的下载地址.
json 文件只是记录了生物的生成, 移动(还有比如说用什么物品驯服, 把xx当作敌人等信息), 游戏读取 json 文件, 然后就是那些鸡呀, 鱼呀的实体.

**Comment by wzh656** [comment]
看起来这个json记录的是实体或方块的属性，我现在方块（现在还没有什么实体）的属性记录在物品`Thing`的`attr`属性，并保存为模板（`template.js`文件的`template`变量），（It's a good idea to make a JSON file）。And模板意味着可能相同ID的方块有不同的属性（如果你修改了的话）
