### ISSUE TITLE
“背包”

### ISSUE THREAD

**Issue by wzh656** [wzh656/MinecraftWeb#5]
“背包”放置物品
物品持有效果
合成功能

**Comment by jason-bowen-zheng** [comment]
背包的话可以使用 Array + JSON 来制作(Minecraft 有27格的背包, 你可以试试如下解决方法):
`[{物品: 数量}, {装备: 耐久}, {装备: 类似 NBT 标签}]`

持有效果, 如果是单人游戏, 拿个方块图片, 旋转一下, 放屏幕右下角(叫HUD).
多人游戏? 算了吧(懒, 我认为 Minecraft 的实现是在人物的手边拿贴图生成一个小的方块, 物品不晓得). 或许可以拿精灵来做(精灵是平面的, 或许可以吧)?

合成, 你可以先试试 2*2 的吧, 我建议你写个 JSON 文件, 把配方写进去, 然后随你了(非常非常麻烦)
> 我合成 JSON 写了大半, OpenGL的GUI不是亿点麻烦(即使 python 的 gloove也是如此, 但是 Java 的 LWJGL 应该有HUD的). 是十分复杂, 要想做好看, 先把贴图集齐吧.

可能 E 键打开背包就没有希望了呢
